### ISSUE TITLE
Break up deis chart into separate charts with dependencies

### ISSUE THREAD

**Issue by mboersma** [deis/charts#1]
As [pointed out](https://github.com/helm/charts/pull/30#issuecomment-156763073) by @bacongobbler, splitting the "deis" chart into multiple charts with dependencies on each other will be more maintainable. This probably requires Helm v0.3.0, which will have dependency resolution.

cc: @gabrtv

**Comment by arschles** [comment]
:+1:

**Comment by rimusz** [comment]
:+1:

**Comment by jchauncey** [comment]
can we close this?
