### ISSUE TITLE
Rename charts from deis-* to workflow-*

### ISSUE THREAD

**Issue by krancour** [deis/charts#126]
Consistent with the directive to brand the PaaS as "Workflow," while "Deis" is the org / umbrella over all our "certified workloads," the chart names should probably change to "deis/workflow" and "deis/workflow-dev".

cc @slack

**Comment by slack** [comment]
Yep! Would also like to move `deis/workflow` to `deis/controller`.

**Comment by rimusz** [comment]
+1

**Comment by krancour** [comment]
@slack so the API component will once again be known as "controller" and Workflow will refer only to the opinionated assemblage of controller and friends?

**Comment by bacongobbler** [comment]
@krancour as far as I know according to [this comment](https://github.com/deis/docs-v2/pull/38#discussion_r54317198), you hit it on the ball. Deis will be the name of the company, and the product name is Workflow. In essence Deis v2 == Workflow.

**Comment by krancour** [comment]
Should the CLI's name change?  It would seem so.

**Comment by bacongobbler** [comment]
Currently tackling this.

**Comment by bacongobbler** [comment]
@krancour I filed https://github.com/deis/workflow-cli/issues/20 to tackle that. As for the other points, see https://github.com/deis/deis/issues/4952 for the follow-up discussion. deis-workflow inside deis-dev has been renamed to deis-controller in #153.

**Comment by helgi** [comment]
Fixed by #157
