### ISSUE TITLE
rename deis-dev components from deis-* to *

### ISSUE THREAD

**Issue by bacongobbler** [deis/charts#155]
This seems ugly and redundant:

```
kubectl --namespace=deis get svc deis-router
```

If it serves no purpose then I propose that we rename service names to their bare names, i.e.

```
kubectl --namespace=deis get svc router
```

I understand that this is a holistic change (since it affects dns and the pod's environment) and probably shouldn't be done pre-beta but we should consider it.

**Comment by jchauncey** [comment]
clearning this milestone for now
