### ISSUE TITLE
Need for bumpver make task

### ISSUE THREAD

**Issue by vdice** [deis/charts#165]
Currently, the version bump logic (for promoting immutable git SHA-based image tags) is entwined in the chart/chart-mate `install` command which requires a running k8s cluster (with the intention of installing the `deis-dev` chart). 

We have at least one case in the `workflow-manager` component where (at this time) we don't desire to run the e2e tests (meaning, no need to bring up a k8s cluster).  All we would like to do is bump the version and make the commit.  Therefore, the request for a `make bumpver` target in charts (which, following the current pattern, would simply invoke the to-be-created [chart-mate](https://github.com/sgoings/chart-mate/issues/7) correlate).

**Comment by sgoings** [comment]
Fixed via #150
