### ISSUE TITLE
e2e test run passed but job failed

### ISSUE THREAD

**Issue by vdice** [deis/charts#182]
In https://ci.deis.io/job/deis-v2-e2e/1034/console the e2e test passed and yet the job was marked failed:

```
Ran 111 of 114 Specs in 2225.458 seconds
SUCCESS! -- 111 Passed | 0 Failed | 2 Pending | 1 Skipped --- PASS: TestTests (2225.47s)
PASS
---------------------------------------------
[info] chart-mate:test: ==> Waiting for pod exit code......(B
0
[warn] chart-mate:test: --> Retrieving information about the kubernetes/deis cluster before exiting...
HEAD detached at de8b45e
nothing to commit, working directory clean
Tearing down kubernetes cluster...
[info] chart-mate:down: ==> Destroying cluster helm-testing-a954...(B
Build step 'Execute shell' marked build as failure
Build did not succeed and the project is configured to only push after a successful build, so no pushing will occur.
[BFA] Scanning build for known causes...
............[BFA] No failure causes found
[BFA] Done. 12s
Finished: FAILURE
```

It seems this was due to a non-zero exit code from `chart-mate:down`.  If so, do we want this to mark the job as a failure? cc @sgoings

**Comment by sgoings** [comment]
Current behavior is correct - we just need to get more info about why this failure happened. It'd probably be best to implement some sort of backtrace so we know what exactly failed.

**Comment by sgoings** [comment]
The actual issue of https://github.com/deis/charts/issues/182 was a situation of having:

`git commit -a -m "chore(versions): ci bumped versions via ${BUILD_URL}"`

Which could return nonzero when there is:

```
nothing to commit, working directory clean
```

Changing to the following makes the job work right:

`git commit -a -m "chore(versions): ci bumped versions via ${BUILD_URL}" || true`
