### ISSUE TITLE
Decide on standard version naming scheme

### ISSUE THREAD

**Issue by arschles** [deis/charts#184]
We should be consistent with version names in manifest in all charts. So far, I've seen the following schemes:
- `version: v2-beta`
- `version: 2.0.0-beta`

**Comment by sgoings** [comment]
My opinions are:

workflow-canary: (work in progress)
- version: canary (mutable)

workflow-beta1: (released)
- version: v2.0.0-beta1 (immutable) (taking after: https://quay.io/repository/deis/controller?tag=latest&tab=tags)

**Comment by jchauncey** [comment]
Closing this as we are already doing one of the following. But a new versioning scheme may be in the works.
