### ISSUE TITLE
Alter charts to allow 100% reproducibility

### ISSUE THREAD

**Issue by technosophos** [deis/charts#199]
The current Helm charts for deis will produce different manifest files each time they are run (actually, each time `generate` is run). Some situations may dictate that the manifests be reproducible.

Likewise, the reason for this is that many templates generate random secrets. Some may prefer to not have random secrets, but to supply their own.

The solution seems to be to simply support template variables for the params that currently allow only generated ones.

```
{{$pw := rand 16}}
Secret: {{default $pw .MyPassword}}
```

That would allow people to supply values via a TOML/YAML/JSON file like we do with the object storage stuff, but would default back to a randomly generated password otherwise.

**Comment by slack** [comment]
This is particularly important if the Workflow install has to be recovered from backups. Controller to database username/password, and builder ssh key (once that moves to secret) at the very least.

Any thoughts on being able to dump a "values" file to hold the results of randomly generated values?

**Comment by smothiki** [comment]
I think this https://github.com/helm/helm/pull/435 fixes overwriting existing generated template files .
cc @mboersma

**Comment by bacongobbler** [comment]
this has since been implemented, because templates cannot be overwritten unless you supply `-f` when running `helm generate` to prevent overwriting those files.
