### ISSUE TITLE
Revisit immutable tag propogation for workflow(-dev/-canary) chart

### ISSUE THREAD

**Issue by vdice** [deis/charts#204]
Our current CI model for deis component changes to the `workflow-dev` chart is as follows:
1. submit component PR
2. CI creates/pushes immutable `git-<SHA>` tag and mutable `canary` tag of said component
3. CI runs e2e tests against updated chart with immutable tag from step 2, sending back success or failure
4. Once PR is green, commit is merged to master
5. Steps 2 and 3 are re-run against this master commit
6. If tests are green, CI pushes commit to `charts` repo substituting immutable tag produced from step 2 for appropriate component Docker image

This process is great in theory.  Unfortunately, in practice, the e2e tests aren't 100% reliable and so some perfectly good component changes (immutable tags) fail to get into the master version of the `workflow-dev` chart in a timely manner.

However, if we went the alternate route of having every component image in the `workflow-dev` chart use the `canary` tag, we run the risk of hitting a situation where the master version of the chart is unstable, since the mutable `canary` tag is produced during component build/deploy stage of CI and _before_ e2e has a chance to notify with a failure.  

These are a few options I see moving forward:
1. Keep model same for now, meaning `workflow-dev` uses immutable tags _but_ chart may not be as fresh
2. Switch to `canary` model so chart is always fresh _but_ offer no guarantees that chart will be stable at any given point
3. Switch to `canary` model _and_ revisit CI build/deploy logic thusly:
   - on component PR build/deploy, _only_ push immutable tag
   - if e2e green (and other prerequisites met, i.e. LGTMs), merge to master
   - on component master merge build/deploy, push immutable tag _and_ `canary` tag
   - run e2e,
     - if green we are all good and `workflow-dev` components already using `canary` tags
     - if red, chart may be unstable/broken and could remain until a fix is provided

The benefit of option 3 is the chance of a broken chart gets moved to a later stage (after greenlit PR gets merged, rather than before) but there still exists a chance of a unstable/broken chart, though hoping the cases will be rarer assuming PR vetting is dependable.

Note: if we go any of the `canary` routes, I vote we change the chart name to `workflow-canary`

Looking for feedback on those 3 options and/or other ideas in this area.  Thanks!

**Comment by helgi** [comment]
I vote option 3 but keeping the workflow-dev name - Stabalizing the development workflow at this point is important

For controller (as an example) locally I only use the immutable tag to update my own registry when I'm developing so that I know what branch I was working against anyway.

**Comment by jackfrancis** [comment]
My 2 cents:

I like the current model, because it is a persistent reminder that our E2E tests are currently non-deterministic. Recent work on our E2E implementation has improved runtimes, so I think it's reasonable to expect the merger to investigate failed post-merge E2E test failures (retry, take notes, etc), and to use that investigation towards a more deterministic E2E paradigm.

I don't think 100% E2E tests are realistic, but I dislike the idea of building rather complicated processes to account for mysterious E2E failure because however clever we are in working around such mysteries, we  will end up in the situation where mystery is institutionalized: "E2E tests are flaky and we don't trust them and that is just that." Now is the time to at least aim for better than that.

**Comment by gabrtv** [comment]
Why are we using `canary` builds at all?  Not only are mutable tags a widely recognized Docker anti-pattern, they're a disaster from a bug reporting standpoint.

>  Unfortunately, in practice, the e2e tests aren't 100% reliable and so some perfectly good component changes (immutable tags) fail to get into the master version of the workflow-dev chart in a timely manner.

Why don't we put the effort into fixing this?

**Comment by arschles** [comment]
my $0.2 - we should put effort into speeding and determinizing (yes, I made that word up) our e2e tests, and remove `canary`. Right now, it just seems like these tags are a band-aid on this larger problem of e2e testing...

Real example: we don't `go build` our CLI binaries and upload them to `deis-canary` on Bintray before we run `go test`.

**Comment by bacongobbler** [comment]
I'm happy with option 1 and fixing up CI to deploy git SHAs in a timely manner through enhancements to the test suite. If we can make the tests 95% reliable then I'd be completely happy with a few hiccups here and there. That's just the nature of end-to-end test suites, unfortunately. Network latency, services going down, etc. All can eventually be fixed.

**Comment by vdice** [comment]
Thank you for the feedback.  It sounds like the consensus is to keep our current process of promoting immutable tags in tact, maintaining focus on e2e determinism.  

Many have questioned the process of pushing mutable/`canary` tags of components along with immutable, therefore https://github.com/deis/workflow-e2e/issues/152 was created to track the proposal to remove this process and let that particular conversation hash out there.
