### ISSUE TITLE
ginkgo node number configurable in deis-tests-parallel chart

### ISSUE THREAD

**Issue by vdice** [deis/charts#213]
In the [deis-tests-parallel](https://github.com/deis/charts/blob/master/deis-tests-parallel/manifests/deis-tests-parallel-pod.yaml) chart manifest, it would be useful to replace the hard-coded ginkgo `nodes` value (which specifies number of parallel test threads) with an environment variable that can be changed on the fly.

**Comment by jchauncey** [comment]
you can do this now by setting `GINKGO_NODES=<number>`
