### ISSUE TITLE
collapse `deis-tests` and `deis-tests-parallel` into one chart

### ISSUE THREAD

**Issue by vdice** [deis/charts#215]
Unless I'm missing something, I don't believe we need both charts anymore.  (CI defaults to using the parallel version.)

We should collapse them into one `deis-tests` chart (perhaps more properly named to indicate it's role as  the tests chart to pair with the latest/dev version of our workflow chart, `workflow-dev`).  

Ideally, this chart could run the test suites either in serial or in parallel via a configuration, e.g. env var.

**Comment by jchauncey** [comment]
This has already happened so closing this
