### ISSUE TITLE
Add slugbuilder, slugrunner and dockerbuilder image pull policy env vars

### ISSUE THREAD

**Issue by arschles** [deis/charts#223]
They'll vary based on release type

For builder:
- `SLUG_BUILDER_IMAGE_PULL_POLICY`
- `DOCKER_BUILDER_IMAGE_PULL_POLICY`

For controller:
- `SLUG_BUILDER_IMAGE_PULL_POLICY`
- `DOCKER_BUILDER_IMAGE_PULL_POLICY`

cc/ @helgi @kmala

**Comment by arschles** [comment]
This has been completed in [`deis/workflow-beta2`](https://github.com/deis/charts/blob/master/workflow-beta2) [in builder](https://github.com/deis/charts/blob/master/workflow-beta2/tpl/deis-builder-rc.yaml#L39-L42). @helgi does this still need to be done for controller?

**Comment by bacongobbler** [comment]
You can [set these environment variables](https://github.com/deis/controller/blob/70f319f01258f62ccc7515811cf056bd73626998/rootfs/deis/settings.py#L266-L269) in the controller, but I still think these need to be documented in either https://github.com/deis/workflow/pull/139 or a follow-up.

**Comment by arschles** [comment]
ok, I'm punting this to beta4 so we can figure out what to do then

**Comment by arschles** [comment]
@bacongobbler noticed that https://github.com/deis/workflow/pull/139 is still open, but the controller env vars aren't in that PR. Do you plan to add the docs there or elsewhere? Regardless, moving to RC1

**Comment by bacongobbler** [comment]
there's a lot of settings that we can tune, yes. I'll try to add all of the controller tunable settings all at once.
