### ISSUE TITLE
AWS S3 credentials

### ISSUE THREAD

**Issue by sstarcher** [deis/charts#244]
AWS S3 credentials should not be required as they can be gathered from the AWS metadata service on instances running inside of AWS.

**Comment by jchauncey** [comment]
But its possible to use gke for the cluster and s3 for storage. Unless I'm missing the point of the issue.

**Comment by sstarcher** [comment]
@jchauncey yep, and in that situation you should supply aws credentials to access s3.  

I'm saying that the s3 credentials should be optional and not required.

**Comment by kmala** [comment]
fixed by #284
