### ISSUE TITLE
Update chart to reference DEIS_DEBUG env var rename

### ISSUE THREAD

**Issue by slack** [deis/charts#254]
Renamed the debug env var. 

workflow-dev should have default `DEIS_DEBUG=true`
workflow-betaX should have default `DEIS_DEBUG=false`

Refs https://github.com/deis/builder/pull/317
Refs https://github.com/deis/slugbuilder/pull/70

**Comment by jchauncey** [comment]
moving to rc1 with the other PRs that work on this
