### ISSUE TITLE
CR(^M) breaks manifest workflow-v2.2.0 in storage.sh

### ISSUE THREAD

**Issue by riethmayer** [deis/charts#318]
``` sh
$ helmc generate -x manifests workflow-v2.2.0
[ERROR] Failed to complete generation: failed to execute ~/.helmc/workspace/charts/workflow-v2.2.0/tpl/storage.sh (~/.helmc/workspace/charts/workflow-v2.2.0/tpl/generate_params.toml): fork/exec ~/.helmc/workspace/charts/workflow-v2.2.0/tpl/storage.sh: no such file or directory
$ ~/.helmc/workspace/charts/workflow-v2.2.0/tpl/storage.sh
-bash: ~/.helmc/workspace/charts/workflow-v2.2.0/tpl/storage.sh: /bin/bash^M: bad interpreter: No such file or directory
```

I then changed the file encoding to unix (emacs, C-x RET f unix).

```
$ rm -rf ~/.helmc/workspace/charts/workflow-v2.2.0/manifests/*
$ helmc generate -x manifests workflow-v2.2.0
# ---> Ran 16 generators.
```

Not sure why this is happening only to me? Hehe

**Comment by mboersma** [comment]
This appears to be specific to Windows file encoding and isn't something likely to be fixed in Helm classic. The workaround is to save files without ^M line endings.

**Comment by riethmayer** [comment]
I had this problem on a Mac and I had the feeling your file is checked in with ^M line endings for any reason. Thanks for your response, Jan

**Comment by mboersma** [comment]
> your file is checked in with ^M line endings

I don't think so, but I could be off-base here. Didn't mean to close this prematurely though--we just haven't been able to reproduce anything like this, but please re-open it if it's ongoing.
