### ISSUE TITLE
Router change requires us to move monitor stack to deployments

### ISSUE THREAD

**Issue by jchauncey** [deis/charts#329]
https://github.com/deis/router/commit/571dfeacb2fbd1ee21645a1de42d18c103288ad3

**Comment by krancour** [comment]
@jchauncey I don't think this is actually the case.

The commit you're referencing transitions router from looking at it's _own_ RC's annotations to looking at it's _own_ deployment's annotations for discovering it's _own_ configuration.

With respect to all routable services, router still determines configuration by looking at annotations on services with the label `routable=true`.

So, I don't believe any change to the monitoring stack is strictly required to accommodate this.

That being said, I think there are _many_ components (monitor components being among them) that should move to deployments simply for the sake of consistency. See #337

**Comment by mboersma** [comment]
> I don't believe any change to the monitoring stack is strictly required

I'm moving this to the next milestone then, but please feel free to close it if #337 covers everything.

**Comment by jchauncey** [comment]
yeah this ended up being a different problem. Will open a new issue to track the work of converting monitor/logging stack to deployments
