### ISSUE TITLE
snake_case or camelCase-- we should pick one and stick to it

### ISSUE THREAD

**Issue by krancour** [deis/charts#333]
In `generate_params.toml`, there are many places where snake_case has been used to delimit words, but there are _also_ many places where camelCase has been used to the same effect. The overall effect of not having settled on a single convention and stuck to it is that it doesn't look quite as professional as it ought.

Can we pick one convention to use going forward and, remediate occurrences of the other? (In docs, too, where applicable!)

To answer the obvious question about this breaking things... I don't believe it does _unless_ someone were to mix and match manifests from one version and `generate_params.toml` from another.

**Comment by mboersma** [comment]
Let's normalize this for the "new helm" version of Workflow charts. For Helm classic it may be problematic to change them at this point.

**Comment by helgi** [comment]
The decision is to make it snake_case, but only in the new charts @kmala is working on.

Reason behind snake_case is that is easier to read when there is no text highlighting and many software use this format in their configs, see nginx, php, gunicorn and many more.
