### ISSUE TITLE
[Helm v2] update controller chart with `REGISTRATION_MODE`

### ISSUE THREAD

**Issue by rimusz** [deis/charts#355]
Update controller chart with `REGISTRATION_MODE` default as `enabled`.
Add to global `values.yaml` an option to change `REGISTRATION_MODE`

**Comment by helgi** [comment]
If you have that as the default then you'll never be able to register the first user. More than just changing the default is needed here.

**Comment by rimusz** [comment]
oops, fixed

**Comment by rimusz** [comment]
ok, closing this one, it is done in v2.8.0
