### ISSUE TITLE
[Helm v2] update Fluentd chart with optional`syslog_hosts` env vars

### ISSUE THREAD

**Issue by rimusz** [deis/charts#356]
Update `Fluentd` chart with optional `SYSLOG_HOST_1/2`.
Add to global `values.yaml` an option to specify those values if needed.

**Comment by rimusz** [comment]
@kmala any updates on this one?

**Comment by rimusz** [comment]
@kmala any update on this one, will that be in v2.9.0?

**Comment by mboersma** [comment]
@rimusz this isn't in the v2.9.0 release, but we'd be happy to entertain a pull request.

**Comment by rimusz** [comment]
sure, might get that PR soon then

**Comment by rimusz** [comment]
@mboersma as promised:
https://github.com/deis/fluentd/pull/72
https://github.com/deis/workflow/pull/631

**Comment by rimusz** [comment]
closing in favour of https://github.com/deis/fluentd/pull/75
