### ISSUE TITLE
[Helm v2] generate router dhparam secret on each new install

### ISSUE THREAD

**Issue by rimusz** [deis/charts#360]
generate unique router `dhparam` secret on fresh Workflow install

**Comment by krancour** [comment]
I like this idea and had already been wanting to do that, however, the current limitation is on the ability to generate this within a template / using sprig.

I opened https://github.com/Masterminds/sprig/issues/11 to track that.

cc @technosophos

**Comment by krancour** [comment]
One other limitation... generating 2048 bit dhparams can take a very long time (depending on your hardware). That might limit us to generating 1024 bit dhparams. Some operators who would prefer 2048 bit might be better off just providing their own.

**Comment by rimusz** [comment]
by default we can generate 1024 bit dhparams, and have an option in global `values.yaml` to change to 2048 bit

**Comment by kmala** [comment]
@rimusz for now i am just going with the current approach but having an option for the user to specify a new one through the values.yaml file.

**Comment by krancour** [comment]
Going to close this.
