### ISSUE TITLE
[Question] Using this repo with the Helm v2 client

### ISSUE THREAD

**Issue by lostintangent** [deis/charts#367]
I'm probably missing something hugely obvious, but I haven't been able to figure out how to add this repo to my Helm v2 (alpha4) client. When I run `helm repo add https://github.com/deis/charts` (as is mentioned in the readme), I get the following error:

`Error: Looks like https://github.com/deis/charts is not a valid chart repository or cannot be reached: yaml: line 9: mapping values are not allowed in this context`. 

Is there a different repo URL I should be using? I looked in the docs and scoured the net, and wasn't able to find anything. Apologies for the very basic question!

**Comment by helgi** [comment]
Right now this is helm v1 (helm classic) only repo - We are working on the v2 support but it is still a little bit away

**Comment by lostintangent** [comment]
@helgi Ah OK, that makes sense.  I had a hunch that may have been the case, but I wasn't sure. Thanks for confirming!
