### ISSUE TITLE
[Helm v2] option to store router annotations

### ISSUE THREAD

**Issue by rimusz** [deis/charts#374]
Add to global `values.yaml` an option to add router annotations.
Update router chart with optional `annotations` parameter.

Such option is handy for enabling e.g. internal LB `service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0`, which will persist Workflow versions upgrade.

**Comment by bacongobbler** [comment]
Hey @rimusz, have you played around with the new v2 charts? https://github.com/deis/router/tree/master/charts/router should get you started playing around with it. Please give us any feedback you'd like there :)

**Comment by kmala** [comment]
the router annotations are persisted during a workflow upgrade so the question boils down to do you want to have an option to specify in the values.yaml so that the same values file can used to create multiple cluster.

**Comment by rimusz** [comment]
yes, would be nice to have the option to specify in the values.yaml
