### ISSUE TITLE
[Helm v2] option to disable builder

### ISSUE THREAD

**Issue by rimusz** [deis/charts#381]
Would be good to have an option via global `values.yaml` file to disable `builder` components:

```
builder
slugbuilder
```

As in some cases e.g. Workflow prod deployment only `deis pull` is needed.

**Comment by rimusz** [comment]
cc @sgoings any estimate on this one? the feature is really needed :)

**Comment by bacongobbler** [comment]
See https://github.com/kubernetes/helm/issues/1837 for work being done upstream to handle this.

Since helm-classic development has stopped in favour of helm, I'm closing this.
