### ISSUE TITLE
How to customize controller behavior?

### ISSUE THREAD

**Issue by mboersma** [deis/charts#5]
Need a replacement mechanism for things such as `deisctl config controller set registrationEnabled=false`, and documentation for same.

**Comment by bacongobbler** [comment]
Something ugly and dirty:

```
$ kubectl exec deis-workflow-xxxxx etcdctl --peers "$DEIS_ETCD_1_SERVICE_HOST:$DEIS_ETCD_1_SERVICE_PORT_CLIENT" set /deis/controller/registrationEnabled false
```

**Comment by technosophos** [comment]
There's a WIP in helm to add this. It'll support Go templates for this.

**Comment by jchauncey** [comment]
can we close this?

**Comment by bacongobbler** [comment]
yup.
