### ISSUE TITLE
the deis chart needs the django and builder secrets

### ISSUE THREAD

**Issue by arschles** [deis/charts#69]
similar to https://github.com/deis/charts/tree/master/deis-dev/tpl folder in `deis-dev`, the deis chart needs the secrets too

**Comment by helgi** [comment]
That will happen when/if deis-dev moves to deis

**Comment by bacongobbler** [comment]
@helgi you mean post-beta? shall we punt the milestone then?

**Comment by helgi** [comment]
Whatever is considered `beta` needs to have this copied over to

**Comment by bacongobbler** [comment]
I think this is the original issue: https://github.com/deis/controller/blob/745f7e1504ae6cb9374a94d77f37eabe48578788/rootfs/deis/settings.py#L262-L264

Those are hard-coded instead of being provided as kubernetes secrets.

**Comment by helgi** [comment]
https://github.com/deis/controller/blob/745f7e1504ae6cb9374a94d77f37eabe48578788/rootfs/templates/local_settings.py#L6-L10 is the prod version

**Comment by bacongobbler** [comment]
my apologies. My assumptions were based on old code, so yes this has been fixed in deis-dev. When we cut beta the deis chart will have these secrets available so we can close this.
