### ISSUE TITLE
Unable to reach workflow using vagrant

### ISSUE THREAD

**Issue by MaxenceAdnot** [deis/charts#77]
Hi,

I just tried to start a Deis v2 cluster on Vagrant.
Everything is correctly started using deis chart (not deis-dev) but i'm getting stuck right after having retrieved the router IP.

"kubectl --namespace=deis get svc deis-router" only gives me a Cluster IP starting with 10.X.X.X which cannot be reached outside the cluster so the deis cli is not able to contact the controller behind.

Did I miss something?

**Comment by bacongobbler** [comment]
You should be able to hit the router though the host. I believe kubernetes will set up the machines on a bridged host-only network, but other machines on the same network shouldn't be able to use the cluster IP. I'm sure there must be a way to play around with the config to make the cluster start on the bridged network.

**Comment by MaxenceAdnot** [comment]
Ok, I'm using the OS X tool from @rimusz (https://github.com/rimusz/coreos-osx-kubernetes-cluster) to test Deis v2. What are you using to test it with Vagrant ?

**Comment by bacongobbler** [comment]
Ah, I haven't used his tool before :)

I just used Google's docs on provisioning a Vagrant cluster [here](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/vagrant.md).

**Comment by jchauncey** [comment]
@MaxenceAdnot you need to have a way to resolve dns to your cluster. I use dnsmasq for mine. There really isnt any difference in provisioning the cluster with @rimusz tool vs the vagrant cluster in the google docs.

**Comment by MaxenceAdnot** [comment]
@jchauncey thank you for the answer but I don't understand why I need a DNS service :/ Using deis.IP.xip.io is not sufficient ? 
It seems that the cluster IP (10.x.x.x) is not reachable from my host (my mac running vagrant)

**Comment by jchauncey** [comment]
Yeah that will work too. You need to point that to the host IP that router
is running on (the IP assigned to the vagrant box itself)

**Comment by MaxenceAdnot** [comment]
I think I've already tried to use the deis.IP.xip.io replacing IP with each one of the 3 machines IPs (just to be sure) launched by the @rimusz tool but I'll try again and let you know. 

Another question: what are the specs (CPU cores/ RAM needed to run Deis v2 ?

**Comment by jchauncey** [comment]
@rimusz has another tool called [kube-solo](https://github.com/TheNewNormal/kube-solo-osx) that stands up a single coreos vm (using xhyve - vm without virtualbox) and I can run the deis-dev chart (v2-beta) without any issues on my 2015 macbook pro with 16 gigs of ram.

**Comment by jchauncey** [comment]
@MaxenceAdnot try this tool  - https://github.com/TheNewNormal/kube-cluster-osx It is the replacement what the one you are using.

**Comment by MaxenceAdnot** [comment]
Thank you for the replacement tool !

My 2015 macbook pro only has 8gigs of ram, I'll see if it works or not.

**Comment by bacongobbler** [comment]
fwiw I've been testing successfully on my 8GB laptop without issues (on v1 the whole host died when booting up the builder until I forced a reboot)

**Comment by MaxenceAdnot** [comment]
Yep deis v1 was too big for a little 8gigs Macbook Pro (got a HP G5 with much more RAM for hacking on Deis) that's why I asked for the required specs earlier. 

I'll try the new tool (https://github.com/TheNewNormal/kube-cluster-osx) with deis v2 in a few hours and I'll tell you what :)

**Comment by MaxenceAdnot** [comment]
It's working perfectly !!! Thank you for your time.
